/*
 * r_baked.h — pre-computed DOOM texture column tables, generated by
 * tools/bake_textures.py and emitted as a const array in main/baked_textures.c.
 *
 * On a no-PSRAM ESP32-C6 we cannot afford to spend ~64 KiB of zone holding
 * texturecolumnlump[] and texturecolumnofs[] arrays at runtime. The tables
 * are deterministic from the WAD, so we precompute them offline and let
 * the linker drop them into flash. r_data.c::R_InitTextures then assigns
 * texturecolumnlump[i]/texturecolumnofs[i] to point at flash, and skips
 * the per-texture R_GenerateLookup() call entirely.
 *
 * IMPORTANT: the bake is keyed to a specific WAD. If you flash a different
 * WAD than the one you baked against, texture rendering will be garbage.
 * Re-run tools/bake_textures.py whenever the WAD changes.
 */
#ifndef R_BAKED_H
#define R_BAKED_H

typedef struct {
    short                  width;
    short                  height;
    int                    compositesize;
    const short           *columnlump;   /* width entries */
    const unsigned short  *columnofs;    /* width entries */
} baked_texture_t;

extern const baked_texture_t baked_textures[];
extern const int             baked_numtextures;

#endif /* R_BAKED_H */
