#!/usr/bin/env python3
"""
bake_textures.py — pre-compute DOOM texture column lookup tables and
emit them as `const` C arrays so they live in flash (.rodata), not RAM.

This is the RP2040-DOOM trick: the column tables (texturecolumnlump[]
and texturecolumnofs[]) are deterministic from the WAD. There's no
reason to spend ~64 KiB of zone holding them at runtime when we can
embed them in the firmware image.

R_GenerateLookup's algorithm is reproduced here verbatim — same patch
iteration order, same `+3` offset on colofs, same single-patch vs.
multi-patch (`-1`) marking, same compositesize accumulation.

Usage:
    python3 tools/bake_textures.py path/to/DOOM1.WAD > main/baked_textures.c
"""
import struct
import sys


def parse_directory(wad_path):
    with open(wad_path, "rb") as f:
        data = f.read()
    if data[:4] not in (b"IWAD", b"PWAD"):
        sys.exit("error: %r is not a WAD (sig=%r)" % (wad_path, data[:4]))
    numlumps, infotableofs = struct.unpack("<II", data[4:12])
    lumps = []
    for i in range(numlumps):
        e = data[infotableofs + i * 16: infotableofs + (i + 1) * 16]
        ofs, sz, name8 = struct.unpack("<II8s", e)
        name = name8.rstrip(b"\x00").decode("ascii", "replace").upper()
        lumps.append((name, ofs, sz))
    return data, lumps


def find_lump_last(lumps, name):
    """W_CheckNumForName scans backwards, so last match wins."""
    name = name.upper()
    last = -1
    for i, (n, _, _) in enumerate(lumps):
        if n == name:
            last = i
    return last


def main():
    if len(sys.argv) < 2:
        sys.exit("usage: bake_textures.py <DOOM1.WAD>")
    wad_path = sys.argv[1]
    data, lumps = parse_directory(wad_path)

    # ── PNAMES ──────────────────────────────────────────────────────────
    pi = find_lump_last(lumps, "PNAMES")
    if pi < 0:
        sys.exit("PNAMES lump not found in WAD")
    _, p_off, _ = lumps[pi]
    nummappatches = struct.unpack("<I", data[p_off:p_off + 4])[0]
    patch_names = [
        data[p_off + 4 + i * 8: p_off + 4 + (i + 1) * 8]
        .rstrip(b"\x00").decode("ascii", "replace").upper()
        for i in range(nummappatches)
    ]
    # patchlookup[i] = lump index of patch with name patch_names[i] (-1 if missing)
    patchlookup = [find_lump_last(lumps, n) for n in patch_names]
    # First valid patch — used as the substitute for missing patches,
    # matching our r_data.c fallback.
    fallback_lump = next((p for p in patchlookup if p >= 0), -1)
    if fallback_lump < 0:
        sys.exit("no valid patch lumps found — bake cannot proceed")

    # ── TEXTURE1 (always) + TEXTURE2 (full / commercial DOOM only) ─────
    # r_data.c::R_InitTextures reads TEXTURE1 then optionally TEXTURE2,
    # concatenating them: numtextures = numtextures1 + numtextures2, with
    # texture index 0..numtextures1-1 served from TEXTURE1 and the rest
    # from TEXTURE2. Our baked output must match this ordering exactly.
    tex_lumps = []
    ti = find_lump_last(lumps, "TEXTURE1")
    if ti < 0:
        sys.exit("TEXTURE1 lump not found in WAD")
    _, t_off, _ = lumps[ti]
    n1 = struct.unpack("<I", data[t_off:t_off + 4])[0]
    tex_lumps.append(("TEXTURE1", t_off, n1))
    ti2 = find_lump_last(lumps, "TEXTURE2")
    if ti2 >= 0:
        _, t2_off, _ = lumps[ti2]
        n2 = struct.unpack("<I", data[t2_off:t2_off + 4])[0]
        tex_lumps.append(("TEXTURE2", t2_off, n2))
    numtextures = sum(n for _, _, n in tex_lumps)

    # ── Generate per-texture column tables ──────────────────────────────
    out = []
    out.append("/* Auto-generated by tools/bake_textures.py from %s.\n"
               " * Edit the script, not this file. */\n"
               % wad_path.split("/")[-1])
    out.append('#include "r_baked.h"\n\n')

    summary = []
    total_collump_bytes = 0
    total_colofs_bytes = 0

    # Walk both TEXTURE lumps in order, emitting a single contiguous
    # 0..numtextures-1 table.
    global_ti = 0
    for tex_lump_name, t_off, num in tex_lumps:
      tex_offsets = struct.unpack(
          "<%di" % num, data[t_off + 4: t_off + 4 + num * 4]
      )
      for local_ti in range(num):
        ti = global_ti
        global_ti += 1
        td = t_off + tex_offsets[local_ti]
        name8 = data[td:td + 8].rstrip(b"\x00").decode(
            "ascii", "replace").upper()
        # masked at td+8..td+12 (unused)
        width, height = struct.unpack("<hh", data[td + 12:td + 16])
        # obsolete columndirectory pointer at td+16..td+20 (unused).
        # NOTE: original DOOM source declared this as `void **`; on the
        # 32-bit DOS compiler it was 4 bytes on disk, which is the WAD
        # format. doomgeneric's C struct uses `int obsolete` (4 B) to
        # match — patchcount lands at +20, patches[] at +22.
        patchcount = struct.unpack("<h", data[td + 20:td + 22])[0]

        columnlump = [0] * width
        columnofs = [0] * width
        cover = [0] * width  # patchcount per column

        for pi in range(patchcount):
            pof = td + 22 + pi * 10
            originx, _originy, patch_idx = struct.unpack(
                "<hhh", data[pof:pof + 6])
            # stepdir+colormap at pof+6..pof+10 (unused)

            if 0 <= patch_idx < len(patchlookup):
                lump_num = patchlookup[patch_idx]
            else:
                lump_num = -1
            if lump_num < 0:
                lump_num = fallback_lump  # matches r_data.c substitution

            _, plump_off, plump_size = lumps[lump_num]
            patch_data = data[plump_off:plump_off + plump_size]
            patch_w = struct.unpack("<h", patch_data[0:2])[0]
            # patch_h = struct.unpack("<h", patch_data[2:4])[0]
            patch_columnofs = struct.unpack(
                "<%dI" % patch_w, patch_data[8:8 + patch_w * 4]
            )

            x1 = originx
            x2 = x1 + patch_w
            x = max(0, x1)
            x_end = min(x2, width)
            for col in range(x, x_end):
                cover[col] += 1
                columnlump[col] = lump_num
                # +3 to skip the post header (topdelta, length, unused)
                columnofs[col] = (patch_columnofs[col - x1] + 3) & 0xFFFF

        # ESP32-C6 PORT: vanilla R_GenerateLookup marks multi-patch
        # columns with collump=-1 and a composite offset, so R_GetColumn
        # can later Z_Malloc a composite buffer and overlay all the
        # patches into it. On this badge that allocation reliably fails
        # mid-render (zone is packed once a level loads — TEKWALL1 alone
        # wants 16 KiB contiguous). Fall back to single-patch / last-
        # patch-wins for overlap columns: the column is rendered using
        # whichever patch the iteration above wrote last. Visual cost is
        # missing decals (e.g., light fixtures on TEKWALL1 disappear);
        # functional cost is zero. compositesize stays 0 so r_data.c's
        # R_GenerateComposite never runs.
        compositesize = 0
        uncovered = 0
        multipatch = 0
        for col in range(width):
            if cover[col] == 0:
                columnlump[col] = fallback_lump
                columnofs[col] = 3
                uncovered += 1
            elif cover[col] > 1:
                # leave columnlump[col] / columnofs[col] as set by the
                # last patch's loop iteration above — single-patch path.
                multipatch += 1

        if uncovered:
            print("// WARNING: texture %s has %d uncovered column(s)" %
                  (name8, uncovered), file=sys.stderr)

        # Emit C arrays. Use 32-bit ints for compositesize since width
        # is bounded but compositesize can briefly exceed 65535 during
        # accumulation (R_GenerateLookup I_Errors at 64K, so we mirror).
        out.append("/* %3d  %-8s %3dx%-3d  patches=%d  composite=%d%s */\n"
                   % (ti, name8, width, height, patchcount, compositesize,
                      "  UNCOVERED!" if uncovered else ""))
        out.append("static const short tex_%d_collump[%d] = {"
                   % (ti, width))
        for i, v in enumerate(columnlump):
            if i % 16 == 0:
                out.append("\n   ")
            out.append(" %d," % v)
        out.append("\n};\n")
        out.append("static const unsigned short tex_%d_colofs[%d] = {"
                   % (ti, width))
        for i, v in enumerate(columnofs):
            if i % 16 == 0:
                out.append("\n   ")
            out.append(" %d," % v)
        out.append("\n};\n\n")

        total_collump_bytes += width * 2
        total_colofs_bytes += width * 2
        summary.append((ti, name8, width, height, compositesize))

    # ── Index table ─────────────────────────────────────────────────────
    out.append("const baked_texture_t baked_textures[] = {\n")
    for ti, name, width, height, compsize in summary:
        out.append("    { %d, %d, %d, tex_%d_collump, tex_%d_colofs },"
                   "  /* %d %s */\n"
                   % (width, height, compsize, ti, ti, ti, name))
    out.append("};\n\n")
    out.append("const int baked_numtextures = %d;\n" % numtextures)

    sys.stdout.write("".join(out))
    print(
        "// Bake summary: %d textures, %d B collump + %d B colofs = %d KiB flash"
        % (numtextures, total_collump_bytes, total_colofs_bytes,
           (total_collump_bytes + total_colofs_bytes) // 1024),
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
